from appium import webdriver
from appium.options.android import UiAutomator2Options

SERVER_URL_BASE = "http://127.0.0.1:4723"


def android_w3c_driver() -> "WebDriver":
    """Return a W3C driver which is generated by a mock response for Android

    Returns:
        `webdriver.webdriver.WebDriver`: An instance of WebDriver
    """

    desired_caps = {
        "platformName": "Android",
        "deviceName": "M2007J17C",
        "app": "ApiDemos-debug.apk",
        "automationName": "UIAutomator2",
    }

    driver = webdriver.Remote(
        SERVER_URL_BASE, options=UiAutomator2Options().load_capabilities(desired_caps)
    )
    return driver
